version: '3'
#**************************************************************
# integration level test agents                                *
#***************************************************************

services:
  #*************************************************************
  # agent: acapy agent loaded with plugin                      *
  # for testing                                                *
  #*************************************************************

  agent:
    image: acapy-plugin-toolbox
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    environment:
      ACAPY_TOOLBOX_LOG_LEVEL: DEBUG
    ports:
      - "3001:3001"
    command: >
      start -it acapy_plugin_toolbox.http_ws 0.0.0.0 3000 -ot http
      -e http://agent:3000
      --admin 0.0.0.0 3001 --admin-insecure-mode
      --plugin acapy_plugin_toolbox
      --genesis-url https://raw.githubusercontent.com/sovrin-foundation/sovrin/master/sovrin/pool_transactions_builder_genesis
      --wallet-type indy
      --wallet-name default
      --wallet-key "insecure, for use in testing only"
      --auto-provision
      --auto-ping-connection
      --monitor-ping
      --auto-store-credential
      --preserve-exchange-records

  echo:
    image: dbluhm/echo-agent:6c22a88
    ports:
      - "3002:3002"
    command: --host 0.0.0.0 --port 3002 --log-level debug

  #*************************************************************
  # tester: drives tests for acapy_plugin_toolbox in a         *
  # "Juggernaut" fashion!                                      *
  #*************************************************************

  tests:
    container_name: juggernaut
    build:
      context: .
    environment:
      - WAIT_BEFORE_HOSTS=3
      - WAIT_HOSTS=agent:3000,echo:3002
      - WAIT_HOSTS_TIMEOUT=60
      - WAIT_SLEEP_INTERVAL=1
      - WAIT_HOST_CONNECT_TIMEOUT=30
      - AGENT_HOST=agent
      - AGENT_PORT=3000
      - AGENT_BACKCHANNEL_PORT=3001
      - SUITE_ENDPOINT=http://echo:3002
      - SUITE_HOST=echo
      - SUITE_PORT=3002
    depends_on:
      - agent
      - echo