version: "3"
services:
  tunnel:
    image: dbluhm/agent-tunnel
    command: -s agent:3000 -p 4040 -h ${AGENT_TUNNEL_HOST}
    ports:
      - 4040:4040
  agent:
    image: acapy-toolbox
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    volumes:
      - ./acapy-endpoint.sh:/acapy-endpoint.sh:ro,z
      - ./configs:/home/indy/configs:ro,z
    environment:
      TUNNEL_ENDPOINT: http://tunnel:4040
    entrypoint: >
      /bin/sh -c '/acapy-endpoint.sh aca-py "$$@"' --
    command: >
      start --arg-file configs/default.yml
