version: "3"
services:
  tunnel-doctor:
    image: dbluhm/agent-tunnel
    command: -s agent-doctor:3000 -p 4040 -h ${AGENT_TUNNEL_HOST}
  agent-doctor:
    image: acapy-toolbox
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    volumes:
      - ./acapy-endpoint.sh:/acapy-endpoint.sh:ro,z
      - ./configs:/home/indy/configs:ro,z
    environment:
      TUNNEL_ENDPOINT: http://tunnel-doctor:4040
      # Modify for more log output
      ACAPY_TOOLBOX_LOG_LEVEL: WARNING
    ports:
      - "3001:3001"
    entrypoint: >
      /bin/sh -c '/acapy-endpoint.sh aca-py "$$@"' --
    command: start --arg-file ./configs/doctor.yml

  tunnel-patient:
    image: dbluhm/agent-tunnel
    command: -s agent-patient:3002 -p 4040 -h ${AGENT_TUNNEL_HOST}
  agent-patient:
    image: acapy-toolbox
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    volumes:
      - ./acapy-endpoint.sh:/acapy-endpoint.sh:ro,z
      - ./configs:/home/indy/configs:ro,z
    environment:
      TUNNEL_ENDPOINT: http://tunnel-patient:4040
      # Modify for more log output
      ACAPY_TOOLBOX_LOG_LEVEL: WARNING
    ports:
      - "3003:3003"
    entrypoint: >
      /bin/sh -c '/acapy-endpoint.sh aca-py "$$@"' --
    command: start --arg-file ./configs/patient.yml

  tails-server:
    image: dbluhm/indy-tails-server:latest
    ports:
      - 6543:6543
    command: >
      tails-server
        --host 0.0.0.0
        --port 6543
        --storage-path ${STORAGE_PATH:-/tmp/tails-files}
        --log-level ${LOG_LEVEL:-INFO}
